import type { Metadata } from "next";
import Header from "@/app/components/layouts/Header";
import Footer from "@/app/components/layouts/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="flex flex-col min-h-screen bg-gray-100">
        <div className="relative z-10">
          <Header />
        </div>
        <main className="flex-grow">{children}</main>
        <div className="relative z-10">
          <Footer />
        </div>
      </body>
    </html>
  );
}
