import type { Metadata } from "next";
import Header from "@/app/components/layouts/Header";
import Footer from "@/app/components/layouts/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <div className="relative z-10">
          <Header />
        </div>
        <div className="flex flex-col min-h-screen bg-gray-100">
          <div className="flex-grow flex">
            <link
              rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.25.0/tocbot.css"
            />
            <main className="flex-grow bg-gray-100">{children}</main>
          </div>
          <div className="relative z-10">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
